M48
; DRILL file {KiCad 9.0.4} date 2025-09-02T10:18:34-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-02T10:18:34-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
%
G90
G05
T1
X115.1Y-88.36
T2
X104.75Y-110.25
X118.25Y-81.25
T1
G00X108.05Y-88.36
M15
G01X107.75Y-88.36
M16
G05
M30
